spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Board-v2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  messages:
    basename: messages,errors
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 60
